// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsRmRtbZlSqJ1KFCFEOlFWPhC0g-vlZw',
    appId: '1:435338290506:web:ad55f73064321ebf878db3',
    messagingSenderId: '435338290506',
    projectId: 'school-ride-app-883fe',
    authDomain: 'school-ride-app-883fe.firebaseapp.com',
    storageBucket: 'school-ride-app-883fe.firebasestorage.app',
    measurementId: 'G-KY3HYML932',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXyAPaXDxQh3HMpNO6ltOwh2rbySj82Q4',
    appId: '1:435338290506:android:9ca2843f676d8776878db3',
    messagingSenderId: '435338290506',
    projectId: 'school-ride-app-883fe',
    storageBucket: 'school-ride-app-883fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACf50V8AwzDYoxaVArHX0_IVae1nWOM8o',
    appId: '1:435338290506:ios:261c97c552e85007878db3',
    messagingSenderId: '435338290506',
    projectId: 'school-ride-app-883fe',
    storageBucket: 'school-ride-app-883fe.firebasestorage.app',
    iosBundleId: 'com.example.schoolrideMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACf50V8AwzDYoxaVArHX0_IVae1nWOM8o',
    appId: '1:435338290506:ios:261c97c552e85007878db3',
    messagingSenderId: '435338290506',
    projectId: 'school-ride-app-883fe',
    storageBucket: 'school-ride-app-883fe.firebasestorage.app',
    iosBundleId: 'com.example.schoolrideMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJsRmRtbZlSqJ1KFCFEOlFWPhC0g-vlZw',
    appId: '1:435338290506:web:591c8d479789819e878db3',
    messagingSenderId: '435338290506',
    projectId: 'school-ride-app-883fe',
    authDomain: 'school-ride-app-883fe.firebaseapp.com',
    storageBucket: 'school-ride-app-883fe.firebasestorage.app',
    measurementId: 'G-EBL4XRW4CL',
  );
}
